### ISSUE TITLE
Password Replace Error

### ISSUE THREAD

**Issue by mariodaelizabeth** [dank/node-csgorc#4]
Hello,
Thank you for your contribution to create this script :)
Could you help me mate for this case please ?

--------------------------------------------------------------------------------
root@vps-1:~/node-csgorc# node app.js
SteamID64: xxxxxxxxxxxxxxxxxx

[1] Report
[2] Commend
[0] CANCEL

Choose one from list [1, 2, 0]: 2
[BOT01] Logging in...
[BOT02] Logging in...
[BOT03] Logging in...
[BOT04] Logging in...
[BOT05] Logging in...
[BOT06] Logging in...
[BOT07] Logging in...
[BOT08] Logging in...
[BOT09] Logging in...
[BOT10] Logging in...
[BOT11] Logging in...
/root/node-csgorc/app.js:28
      password: param[1].replace(/[\n\t\r]/g,"")
                        ^

TypeError: Cannot read property 'replace' of undefined
    at /root/node-csgorc/app.js:28:25
    at Array.forEach (native)
    at Object.<anonymous> (/root/node-csgorc/app.js:19:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
root@VPS-1:~/node-csgorc#
--------------------------------------------------------------------------------

Node version : v5.12.0
NPM version : 3.8.6
All of my bots work fine and no wrong password. Help me please

Thank You :D

**Comment by ghost** [comment]
How does your accounts file look like?
It needs to be in this format:
account1:password1
account2:password2

**There has to be a line break after each account:password field!**

**Comment by mariodaelizabeth** [comment]
Thank you for your reply, mate...
This is my accounts.txt look like

BOT01:11PASSa!
BOT02:22PASSb!
BOT03:33PASSc!

I put number, uppercase, lowercase and ! symbol. Should i change password to number and uppercase only ?

**Comment by dank** [comment]
Hey,

Pull the latest change from master and try again please.

Thanks!

**Comment by dank** [comment]
@mariodaelizabeth No, the symbols shouldn't matter. 

Please pull the latest update and try again. It should be fixed.

**Comment by ghost** [comment]
@dank You still need the replace function... It crashes when reading multiple lines because split doesn't trim the carriage return keys.

**Comment by dank** [comment]
@NoTeefy Gotcha. I was not aware. Thanks 😄

**Comment by mariodaelizabeth** [comment]
I got some errors again ....

Choose one from list [1, 2, 0]: 1
Match ID:
[asector01] Logging in...
[asector02] Logging in...
[asector03] Logging in...
[asector04] Logging in...
[asector05] Logging in...
[asector06] Logging in...
[asector08] Logging in...
[asector09] Logging in...
[aldavarizki10] Logging in...
[asector011] Logging in...
[fransid01] Logging in...
[asector09] Logged in!
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './sentry/asector09'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at SteamUser.<anonymous> (/root/node-csgorc/app.js:89:10)
    at emitTwo (events.js:100:13)
    at SteamUser.emit (events.js:185:7)
    at SteamUser.handlers.(anonymous function) (/root/node-csgorc/node_modules/steam/lib/handlers/user/index.js:61:8)
    at SteamUser.<anonymous> (/root/node-csgorc/node_modules/steam/lib/handlers/user/index.js:12:28)
    at emitThree (events.js:115:20)
    at SteamClient.emit (events.js:188:7)

What's wrong with it, mate ?
Could help me ?

**Comment by ghost** [comment]
Please close your issue if your problem got solved (as stated in [https://github.com/dank/node-csgorc/issues/8](https://github.com/dank/node-csgorc/issues/8) )
