### ISSUE TITLE
11 Account for Report

### ISSUE THREAD

**Issue by mariodaelizabeth** [dank/node-csgorc#8]
Hello guys,

I have installed this script and works fine.
I have33 accounts in a file .txt. When i report someone, the script sent 33 report for 1 SteamID64. It should be 11, right ?
How to limit account amount for reporting ?

**Comment by ghost** [comment]
There is no build-in function to achieve this functionality so far. You could separate your accounts into multiple .txt files and pass them by a start parameter or counting the successfull reports up to 11 and then disconnect the program (not the fanciest solution, but it should prevent more than 11 reports for one steamid)

**Comment by mariodaelizabeth** [comment]
aaaah Nice idea bruh...
got it xD

thx dude
