### ISSUE TITLE
no work for me 

### ISSUE THREAD

**Issue by MrLiamMcQ** [dank/node-csgorc#9]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle report@1.0.0~prestart: report@1.0.0
6 silly lifecycle report@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle report@1.0.0~start: report@1.0.0
8 verbose lifecycle report@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle report@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\bob\Desktop\node-csgorc-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\nodejs\;C:\Users\bob\AppData\Local\Microsoft\WindowsApps;C:\Users\bob\AppData\Roaming\npm
10 verbose lifecycle report@1.0.0~start: CWD: C:\Users\bob\Desktop\node-csgorc-master
11 silly lifecycle report@1.0.0~start: Args: [ '/d /s /c', 'node app.js' ]
12 silly lifecycle report@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle report@1.0.0~start: Failed to exec start script
14 verbose stack Error: report@1.0.0 start: `node app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid report@1.0.0
16 verbose cwd C:\Users\bob\Desktop\node-csgorc-master
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error report@1.0.0 start: `node app.js`
22 error Exit status 1
23 error Failed at the report@1.0.0 start script 'node app.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the report package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node app.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs report
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls report
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by dank** [comment]
I have never encountered this bug before however, it doesn't seem like the app is causing it. Try the following:

- Reinstall Node.js. Maybe this [issue](https://github.com/npm/npm/issues/7963) is related.
- Make sure you have ran `npm install` before anything else.

If none of that works, please try cloning a fresh copy of this repo.

**Comment by ghost** [comment]
Update your nodejs and npm to the latest version. This error occurs if you try to build it under nodejs 7.0.
Just run this
npm cache clean -f 
npm install -g n 
n stable

And run it again :)

**Comment by MrLiamMcQ** [comment]
i updated and it dont do that error but i still no work 

am on windows 10 node.js is ver 8

paste bin off out put : https://pastebin.com/qh416Rts

paste bin of  debug log : https://pastebin.com/sA8KwAd7

thanks
